remote_theme: BDHU/minimalist

sidebar:
  - name: default
    link: ./default
  - name: about
    link: ./about
  - name: content
    link: ./content
  - name: challenge
    link: ./#challenge
  - name: random stuff
    link: ./#randomstuff
  - name: design
    link: ./#design
    
